/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS NORMALLY GENERATED BY `npx convex dev` / `npx convex codegen`
 * — see the note at the top of `./server.ts` for why it's hand-written here
 * and when it gets overwritten. If a new file is added under `convex/`
 * (e.g. `convex/http.ts` in Phase 8), a real `npx convex dev` run
 * regenerates this automatically; if still running without a live
 * deployment, add the corresponding `import type * as` + `fullApi` entry
 * below by hand, mirroring the existing two.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.products.upsertProduct;
 * ```
 *
 * @module
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import { anyApi } from "convex/server";
import type * as products from "../products.js";
import type * as transactions from "../transactions.js";

const fullApi: ApiFromModules<{
  products: typeof products;
  transactions: typeof transactions;
}> = anyApi as any;

/**
 * A utility for referencing Convex functions in your app's public API.
 */
export const api: FilterApi<typeof fullApi, FunctionReference<any, "public">> = anyApi as any;

/**
 * A utility for referencing Convex functions in your app's internal API.
 */
export const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">> = anyApi as any;
