/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS NORMALLY GENERATED BY `npx convex dev` / `npx convex codegen`
 * — see the note at the top of `./server.ts` for why it's hand-written here
 * and when it gets overwritten.
 *
 * @module
 */

import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = TableNamesInDataModel<DataModel>;

/**
 * The type of a document stored in Convex.
 *
 * @typeParam TableName - A string literal type of the table name (like "products").
 */
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;

/**
 * An identifier for a document in Convex.
 *
 * @typeParam TableName - A string literal type of the table name (like "products").
 */
export type Id<TableName extends TableNames | SystemTableNames> = GenericId<TableName>;

/**
 * A type describing your Convex data model.
 *
 * This type includes information about what tables you have, the type of
 * documents stored in those tables, and the indexes defined on them.
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
